HotelManagement/Areas/Hotel/Controllers/FrontDeskController.cs
using HotelManagement.Data.Services.FloorServices;
using HotelManagement.Data.Services.FloorServices.Contracts;
using HotelManagement.Data.Services.FrontDeskServices.Contracts;
using HotelManagement.Web.ViewModels.FloorModels;
using HotelManagement.Web.ViewModels.FrontDeskModels;
using HotelManagement.Web.ViewModels.FrontDeskModels.ServiceModels;
using HotelManagement.Web.ViewModels.ReservationsModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HotelManagement.Areas.Hotel.Controllers
{

    /// <summary>
    /// Controller used to see rooms available for reservation.
    /// </summary>

    [Authorize]
    [Area("Hotel")]
    [Authorize(Roles = ("Owner,Director,Manager,Admin,Front Desk,Manager"))]
    public class FrontDeskController : Controller
    {
        private readonly IFrontDeskServices frontDeskServices;

        private readonly IFloorServices floorServices;

        public FrontDeskController(IFrontDeskServices _frontDeskServices, IFloorServices _floorServices)
        {
            frontDeskServices = _frontDeskServices;

            floorServices = _floorServices;
        }

        /// <summary>
        /// Lists all rooms available for reservation based on query params.
        /// </summary>
        /// <param name="query"></param>
        /// <param name="id"></param>
        /// <returns></returns>

        // GET: FrontDeskController/Create
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> FreeRooms([FromQuery] AllFreeRoomsViewModel query, int id)
        {
            if (query.ArrivalDate == null)
            {
                query.ArrivalDate = DateTime.Now;
                query.DepartureDate = DateTime.Now.AddDays(1);
            }



            var queryResult = await frontDeskServices
                .All(query.ArrivalDate,
                    query.DepartureDate,
                    query.RoomSorting,
                    query.RoomType,
                    query.Available,
                    query.SearchTerm,
                    query.CurrentPage,
                    AllFreeRoomsViewModel.RoomsPerPage,
                    id);



            query.TotalRoomsCount = queryResult.TotalRoomsCount;

            query.Rooms = queryResult.Rooms.ToList();

            query.RoomTypes = await floorServices.GetRoomTypes();

            if (query.ArrivalDate >= query.DepartureDate || query.DepartureDate.HasValue == false)
            {
                ModelState.AddModelError("", "Departure date cannot be before arrival date.");

                query.ArrivalDate = DateTime.Now;
                query.DepartureDate = DateTime.Now.AddDays(1);

                return View(query);
            }


            foreach (var room in query.Rooms)
            {

                room.ArrivalDate = query.ArrivalDate;

                room.DepartureDate = query.DepartureDate;
            }


            return View(query);
        }


    }
}

HotelManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

 <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hotel Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HotelManagement.styles.css" asp-append-version="true" />
    <link rel=stylesheet href="~/lib/limonte-sweetalert2/sweetalert2.css" asp-append-version="true" />

</head>

<style>
    
  
    .navbar a:hover, .dropdown:hover .dropbtn {
        background-image: linear-gradient(0deg, rgb(100, 0, 0), rgb(255, 0, 0));
        border-radius: 15px 50px;

    }

    #mainBody{
        background-image: linear-gradient(45deg, #FFFFFF, rgb(204, 255, 255));
    }

    html{
        position:relative; 
        min-height: 100%;
    }
    /*Normalize html and body elements,this style is just good to have*/
    html,body{
        
        margin:0;
        padding:0;
    }
    .pageContentWrapper{
        margin-bottom:100px;/* Height of footer*/
    } 
    .footer{
        position: absolute;
        bottom: 0;
        left: 0;
        right: 0;
        height:55px;
    }

</style>

<body id="mainBody">
<div class="pageContentWrapper">

                        <header>

        
        
                        <nav class="navbar  navbar-expand-sm navbar-toggleable-sm navbar-dark bg-black border-bottom box-shadow mb-3">
                            <div class="container-fluid">
                                <a class="navbar-brand px-4" style="font-size: 30px" asp-area="" asp-controller="Home" asp-action="Index">HotelManagement</a>
                                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                        aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" style="font-size: 25px">
                                    <ul class="navbar-nav flex-grow-1">
                                        @if ((User?.Identity?.IsAuthenticated ?? false))
                                        {

                                            if (User.IsInRole("Human Resources") || User.IsInRole("Admin") || User.IsInRole("Owner") || User.IsInRole("Director"))
                                            {
                                                <partial name="./LayoutPartials/_EmployeesPartial.cshtml" />
                                            }

                                            if (User.IsInRole("Admin") || User.IsInRole("Owner") || User.IsInRole("Director") || User.IsInRole("Front Desk"))
                                            {
                                                <li class="nav-item">
                                                    <a class="nav-link text-white px-4" asp-area="Hotel" asp-controller="FrontDesk" asp-action="FreeRooms"> Front Desk </a>
                                                </li>
                                            }
                                            if ( User.IsInRole("Admin") || User.IsInRole("Owner") || User.IsInRole("Director") || User.IsInRole("Front Desk"))
                                            {
                                                <li class="nav-item">
                                                    <a class="nav-link text-white px-4" asp-area="Reservations" asp-controller="Reservations" asp-action="AllReservations"> Reservations </a>
                                                </li>

                                            }
                                            if (User.IsInRole("Admin") || User.IsInRole("Owner") || User.IsInRole("Director") || User.IsInRole("Front Desk") || User.IsInRole("Housekeeping"))
                                            {
                                                        
                                                <partial name="./LayoutPartials/_FloorsPartial.cshtml" />
                                            }
                                        }
                    
                    
                    
                                    </ul>
                                    <partial name="./LayoutPartials/_LoginPartial.cshtml"/>
                                </div>
                            </div>
                        </nav>
                    </header>
                            <div class="container">
                                <main role="main" class="pb-3">
                                    @RenderBody()
                                </main>
                            </div>
                    
    </div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/lib/limonte-sweetalert2/sweetalert2.js"></script>
@await RenderSectionAsync("Scripts", required: false)

    
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; @DateTime.UtcNow.Year - HotelManagement - <a asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
</body>



</html>