HotelManagement/Areas/Hotel/Controllers/FloorController.cs
using HotelManagement.Data.Services.FloorServices.Contracts;
using HotelManagement.Web.ViewModels.FloorModels;
using HotelManagement.Web.ViewModels.FloorModels.ServiceModels;
using HotelManagement.Web.ViewModels.ManageEmployeesModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HotelManagement.Areas.Hotel.Controllers
{
    /// <summary>
    /// Controller that sorts rooms by floors, mainly used to monitor rooms
    /// </summary>
    [Area("Hotel")]
    [Authorize(Roles = ("Owner,Director,Manager,Admin,Front Desk,Manager"))]
    public class FloorController : Controller
    {
        private readonly IFloorServices floorServices;

        public FloorController(IFloorServices _floorServices)
        {
            floorServices = _floorServices;
        }

        /// <summary>
        /// Returns all rooms based on floor id or query params.
        /// </summary>
        /// <param name="query"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: FloorController
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> All([FromQuery] AllRoomsViewModel query, int id)
        {
            Console.WriteLine(id);

            var queryResult = await floorServices
                .All(query.RoomSorting,
                    query.RoomType,
                    query.Active,
                    query.SearchTerm,
                    query.IsAvailable,
                    query.CurrentPage,
                    AllRoomsViewModel.RoomsPerPage,
                    id);

            query.TotalRoomsCount = queryResult.TotalRoomsCount;

            query.Rooms = queryResult.Rooms.ToList();

            query.RoomTypes = await floorServices.GetRoomTypes();



            return View(query);
        }


    }
}

HotelManagement/Areas/Hotel/Controllers/RoomController.cs
using HotelManagement.Data.Services.RoomServices.Contracts;
using HotelManagement.Web.ViewModels.RoomModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Serilog;
using System.Data;

namespace HotelManagement.Areas.Hotel.Controllers
{

    /// <summary>
    /// Room controller that enables viewing and manipulation of rooms.
    /// </summary>
    [Area("Hotel")]
    [Authorize(Roles = ("Owner,Director,Manager,Admin,Front Desk,Manager"))]
    public class RoomController : Controller
    {
        private readonly IRoomServices roomServices;

        public RoomController(
            IRoomServices _roomServices
            )
        {
            roomServices = _roomServices;
        }

        /// <summary>
        /// Gets the room details.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>View with room details</returns>
        // GET: RoomController/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            var result = new RoomDetailsViewModel();

            try
            {
                result = await roomServices.GetRoomDetailsModelAsync(id);
            }
            catch (ArgumentNullException ex)
            {
                TempData["status"] = 404;

                throw;
            }


            return View(result);
        }



        /// <summary>
        /// Room edit get.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>Edit view for room.</returns>

        // GET: RoomController/Edit/5
        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {

            var model = new RoomEditViewModel();

            try
            {
                model = await roomServices.GetRoomEditViewModelAsync(id);
            }
            catch (ArgumentNullException ex)
            {
                TempData["status"] = 404;

                throw;
            }


            return View(model);
        }


        /// <summary>
        /// Edit post, edits rooms.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        // POST: RoomController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(RoomEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Invalid submit form.");

                return RedirectToAction("Edit", new{id= model.Id});
            }

            int result;

            try
            {
                result = await roomServices.EditRoomWithEditViewModel(model);
            }
            catch (ArgumentNullException e)
            {
                TempData["status"] = 404;

                throw;
            }
            catch (DBConcurrencyException e)
            {
                TempData["status"] = 400;

                throw;
            }
            Log.Logger.Information("User {0} edited room with number {1}", this.User?.Identity?.Name ?? "NAME MISSING", model.RoomNumber);

            return RedirectToAction("Details", "Room", new { id = model.Id.ToString() });
        }


        /// <summary>
        /// Disables room
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // POST: RoomController/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            bool result;
            try
            {
                result = await roomServices.DeleteRoomById(id);
            }
            catch (ArgumentNullException ex)
            {

                TempData["status"] = 404;

                throw;
            }
            catch (OperationCanceledException ex)
            {
                TempData["status"] = 409;

                throw;
            }
            catch (DBConcurrencyException ex)
            {
                TempData["status"] = 400;

                throw;
            }

            Log.Logger.Information("User {0} disabled room with id {1}", this.User?.Identity?.Name ?? "NAME MISSING", id);

            return RedirectToAction(result ? "Details" : "Edit", "Room", new { id });
        }


        /// <summary>
        /// Enables room 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // POST: RoomController/Delete/5
        [HttpGet]
        public async Task<ActionResult> Enable(int id)
        {
            bool result;
            try
            {
                result = await roomServices.EnableRoomById(id);
            }
            catch (ArgumentNullException ex)
            {

                TempData["status"] = 404;

                throw;
            }
            catch (OperationCanceledException ex)
            {
                TempData["status"] = 409;

                throw;
            }
            catch (DBConcurrencyException ex)
            {
                TempData["status"] = 400;

                throw;
            }

            Log.Logger.Information("User {0} enabled room with id {1}", this.User?.Identity?.Name ?? "NAME MISSING", id);

            return RedirectToAction(result ? "Details" : "Edit", "Room", new { id });
        }


        /// <summary>
        /// Sets room status to cleaned
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult> IsCleaned(int id)
        {
            bool result;
            try
            {
                result = await roomServices.IsCleanedAsync(id);
            }
            catch (ArgumentNullException ex)
            {

                TempData["status"] = 404;

                throw;
            }
            catch (OperationCanceledException ex)
            {
                TempData["status"] = 409;

                throw;
            }
            catch (DBConcurrencyException ex)
            {
                TempData["status"] = 400;

                throw;
            }

            Log.Logger.Information("User {0} set status cleaned to room with id {1}", this.User?.Identity?.Name ?? "NAME MISSING", id);

            return RedirectToAction(result ? "Details" : "Edit", "Room", new { id });
        }

        /// <summary>
        /// Sets room status to dirty
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>

        [HttpGet]
        public async Task<ActionResult> IsDirty(int id)
        {
            bool result;
            try
            {
                result = await roomServices.IsDirtyAsync(id);
            }
            catch (ArgumentNullException ex)
            {

                TempData["status"] = 404;

                throw;
            }
            catch (OperationCanceledException ex)
            {
                TempData["status"] = 409;

                throw;
            }
            catch (DBConcurrencyException ex)
            {
                TempData["status"] = 400;

                throw;
            }

            Log.Logger.Information("User {0} set status dirty to room with id {1}", this.User?.Identity?.Name ?? "NAME MISSING", id);

            return RedirectToAction(result ? "Details" : "Edit", "Room", new { id });
        }

        /// <summary>
        /// Sets room status to out of service
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>

        [HttpGet]
        public async Task<ActionResult> OutOfService(int id)
        {
            bool result;

            try
            {
                result = await roomServices.RoomOutOfServiceByIdAsync(id);
            }
            catch (ArgumentNullException ex)
            {

                TempData["status"] = 404;

                throw;
            }
            catch (OperationCanceledException ex)
            {
                TempData["status"] = 409;

                throw;
            }
            catch (DBConcurrencyException ex)
            {
                TempData["status"] = 400;

                throw;
            }


            Log.Logger.Information("User {0} set status OutOfService to room with id {1}", this.User?.Identity?.Name ?? "NAME MISSING", id);

            return RedirectToAction(result ? "Details" : "Edit", "Room", new { id });
        }

        /// <summary>
        /// Sets room status to in service
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>

        [HttpGet]
        public async Task<ActionResult> InService(int id)
        {
            bool result;

            try
            {
                result = await roomServices.RoomInServiceByIdAsync(id);
            }
            catch (ArgumentNullException ex)
            {

                TempData["status"] = 404;

                throw;
            }
            catch (OperationCanceledException ex)
            {
                TempData["status"] = 409;

                throw;
            }
            catch (DBConcurrencyException ex)
            {
                TempData["status"] = 400;

                throw;
            }


            Log.Logger.Information("User {0} set status InService to room with id {1}", this.User?.Identity?.Name ?? "NAME MISSING", id);

            return RedirectToAction(result ? "Details" : "Edit", "Room", new { id });
        }
    }
}

HotelManagement/Areas/Hotel/Views/Room/Details.cshtml
@model HotelManagement.Web.ViewModels.RoomModels.RoomDetailsViewModel

@{
    ViewBag.Title = "Room details";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="container" style="display:inline">
    <div class="row">
        <div class="col-4">
        </div>
        <div class="card col-4 border-0" style="font-size:20px;">
            <p style="font-size:40px;">Room Number: <b><u>@Model.RoomNumber</u></b></p>
            <p style="font-size:40px;">Reservations count: <b><u>@Model.NumberOfReservations</u></b></p>
            <p >Capacity: <b><u>@Model.Capacity</u></b></p>
            <p>Type: @Model.RoomType</p>
            <p>Price per person: @Model.PricePerPerson</p>
            <p>Price on full capacity: @Model.PriceOnFullCapacity</p>


            @if (Model.DeletedOn != null && Model.IsActive == false)
            {
                <p>Deleted on: <b>@Model.DeletedOn</b></p>
            }
            <p><b>Active: @(Model.IsActive ? "Active" : "Disabled")</b>
                @if (@Model.IsActive)
                {
                    
                    <a asp-controller="Room" method="get" asp-action="Delete" asp-route-id="@Model.Id"
                       class="btn btn-danger">Disable</a>
                }
                else
                {
                    <a asp-controller="Room" asp-action="Enable" asp-route-id="@Model.Id"
                       class="btn btn-info">Enable</a>
                }
            </p>

            <p><b>Occupation: @(Model.IsOccupied ? "Occupied" : "Free")</b></p>

            <p><b>Cleaned: @(Model.IsCleaned ? "Cleaned" : "Dirty")</b>
                @if (!@Model.IsCleaned)
                {

                    <a asp-controller="Room" method="get" asp-action="IsCleaned" asp-route-id="@Model.Id"
                       class="btn btn-success">Cleaned</a>
                }
                else
                {
                    <a asp-controller="Room" asp-action="IsDirty" asp-route-id="@Model.Id"
                       class="btn btn-warning">Dirty</a>
                }
                </p>
            

            <p><b>Service: @(Model.IsOutOfService ? "Out of Service" : "In service")</b>
                @if (@Model.IsOutOfService)
                {

                    <a asp-controller="Room" method="get" asp-action="InService" asp-route-id="@Model.Id"
                   class="btn btn-success">In Service</a>
                }
                else
                {
                    <a asp-controller="Room" asp-action="OutOfService" asp-route-id="@Model.Id"
                   class="btn btn-warning">Out of Service</a>
                }
            </p>

          <p>Created on: @Model.CreatedOn</p>


           <p></p>

            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">Currently viewing as: @User.Identity?.Name</h5>
                </div>
            </div>
            <p></p>
            <div>
                <a asp-controller="Room" asp-action="Edit" asp-route-id="@Model.Id"
                   class="btn btn-success col-5">Edit</a>
                
                
            </div>
            <div>
                @if (Model.EditedOn != null)
                {
                    <p>Edited on: <b>@($"{Model.EditedOn:d}")</b></p>
                }
            </div>
            

        </div>
    </div>
</div>

HotelManagement/Areas/Hotel/Views/Room/Edit.cshtml
@model HotelManagement.Web.ViewModels.RoomModels.RoomEditViewModel

@{
    ViewData["Title"] = $"Edit room";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Edit Room</h1>

<h4>Room number: @Model.RoomNumber</h4>
<hr />
<div class="row" style="font-size:17px">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @if (TempData["Error"] != null)
            {
                <div asp-validation-summary="None" class="text-danger">@TempData["Error"].ToString()</div>
            }
            <div class="form-group">
                <label asp-for="RoomNumber" class="control-label"></label>
                <input asp-for="RoomNumber" class="form-control" />
                <span asp-validation-for="RoomNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <p></p>
         
            <p><i>(Current room type: @Model?.RoomTypeDtos?.Where(rt => rt.Id == Model.currentRoomTypeId)?.FirstOrDefault()?.Type)</i></p>

            <div class="mb-3">
                <label asp-for="@Model.RoomTypeDtoId" class="form-label">Room type</label>
                <select asp-for="@Model.RoomTypeDtoId" class="form-control">

                    @foreach (var rt in Model.RoomTypeDtos)
                    {
                        if (rt.Id == Model.currentRoomTypeId)
                        {
                            <option value="@rt.Id" selected>@rt.Type</option>
                        }
                        else
                        {
                            <option value="@rt.Id">@rt.Type</option>
                        }
                        
                    }
                </select>
                <span asp-validation-for="RoomTypeDtoId" class="text-danger"></span>
            </div>

            <p><i>(Current floor#: @Model?.FloorDtos?.Where(f => f.Id == Model.currentFloorId)?.FirstOrDefault()?.FloorNumber)</i></p>

            <div class="mb-3">
                <label asp-for="@Model.FloorId" class="form-label">Floor</label>
                <select asp-for="@Model.FloorId" class="form-control">

                    @foreach (var f in Model.FloorDtos)
                    {
                        
                        <option value="@f.Id">@f.FloorNumber</option>
                    }
                </select>
                <span asp-validation-for="FloorId" class="text-danger"></span>
            </div>

            <p></p>
            <input asp-for="Id" class="visually-hidden"/>

            <div class="form-group row">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
</div>
     
</div>

<div>
    <a asp-controller="Floor" asp-action="All" asp-route-id="@Model.currentFloorId">Back to Floor</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}